CREATE DATABASE COMPANY;
USE COMPANY;
CREATE TABLE PRODUCT (
ID INT PRIMARY KEY,
NAME varchar(100) NOT NULL,
DESCR TEXT,
SKU VARCHAR(100),
CATEGORY_ID INT,
INVENTORY_ID INT,
PRICE INT,
DISCOUNT_ID INT,
CREATED_AT TIMESTAMP,
MODIFIED_AT TIMESTAMP,
DELETED_AT TIMESTAMP,
FOREIGN KEY(CATEGORY_ID) REFERENCES PRODUCT_CATEGORY(ID),
FOREIGN KEY(INVENTORY_ID) REFERENCES PRODUCT_INVENTORY(ID),
FOREIGN KEY(DISCOUNT_ID) REFERENCES DISCOUNT(ID)
);
CREATE TABLE PRODUCT_CATEGORY(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
DESCR TEXT,
CREATED_AT TIMESTAMP,
MODIFIED_AT TIMESTAMP,
DELETED_AT TIMESTAMP);

CREATE TABLE PRODUCT_INVENTORY(
ID INT PRIMARY KEY,
QUANTITY INT,
CREATED_AT TIMESTAMP,
MODIFIED_AT TIMESTAMP,
DELETED_AT TIMESTAMP);

CREATE TABLE DISCOUNT(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
DESCR TEXT,
DISCOUNT_PERCENT DECIMAL,
ACTIVE BOOLEAN,
CREATED_AT TIMESTAMP,
MODIFIED_AT TIMESTAMP,
DELETED_AT TIMESTAMP);



